Repository SubZero-Robotics/2023-CommandRobot, pull requests merged in 2023-02, with the labels that each got.

#17 Create workflow for code formatting
  .clang-format
  .github/workflows/wpiformat.yml
  src/main/cpp/Robot.cpp
  src/main/cpp/RobotContainer.cpp
  src/main/cpp/commands/Autos.cpp
  src/main/cpp/commands/ExampleCommand.cpp
  src/main/cpp/subsystems/ExampleSubsystem.cpp
  src/main/include/Robot.h
  src/main/include/RobotContainer.h
  src/main/include/commands/ExampleCommand.h
  src/main/include/subsystems/ExampleSubsystem.h
  src/test/cpp/main.cpp
Labels: enhancement, P2

#22 Differential drive using falcon500
  .vscode/settings.json
  build.gradle
  gradlew
  src/main/cpp/RobotContainer.cpp
  src/main/cpp/commands/DefaultDrive.cpp
  src/main/cpp/commands/DriveResetOdometry.cpp
  src/main/cpp/subsystems/DriveSubsystem.cpp
  src/main/include/Constants.h
  src/main/include/RobotContainer.h
  src/main/include/commands/DefaultDrive.h
  src/main/include/commands/DriveResetOdometry.h
  src/main/include/subsystems/DriveSubsystem.h
  vendordeps/NavX.json
  vendordeps/Phoenix.json
  vendordeps/Phoenix5-frc2023-latest.json
Labels: roboRIO, feature

#21 RGB LED Controller
  .github/PULL_REQUEST_TEMPLATE
  hardware/led controller/2023 SubZero LED Controller Gerber.zip
  hardware/led controller/CAD/case.stl
  hardware/led controller/led controller/fp-info-cache
  hardware/led controller/led controller/led controller.kicad_pcb
  hardware/led controller/led controller/led controller.kicad_prl
  hardware/led controller/led controller/led controller.kicad_pro
  hardware/led controller/led controller/led controller.kicad_sch
  ledcontroller/controller/.gitignore
  ledcontroller/controller/.vscode/extensions.json
  ledcontroller/controller/include/Commands.h
  ledcontroller/controller/include/Patterns.h
  ledcontroller/controller/include/README
  ledcontroller/controller/lib/README
  ledcontroller/controller/platformio.ini
  ledcontroller/controller/src/Patterns.cpp
  ledcontroller/controller/src/main.cpp
  ledcontroller/controller/test/README
  ledcontroller/testclient/.gitignore
  ledcontroller/testclient/.vscode/extensions.json
  ledcontroller/testclient/include/README
  ledcontroller/testclient/lib/README
  ledcontroller/testclient/platformio.ini
  ledcontroller/testclient/src/main.cpp
  ledcontroller/testclient/test/README
  src/main/cpp/subsystems/LEDController.cpp
  src/main/include/subsystems/LEDController.h
Labels: feature
